#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

ORG_ID="${SUPABASE_ORG_ID:-iweolkzzecmippoukxct}"
PROJECT_NAME="${SUPABASE_PROJECT_NAME:-limeboard}"
REGION="${SUPABASE_REGION:-us-west-1}"

echo "==> LimeBoard Supabase setup"
echo ""

if ! command -v supabase >/dev/null; then
  echo "Install Supabase CLI: brew install supabase/tap/supabase"
  exit 1
fi

# --- Step 1: create + link project ---
if [[ ! -f supabase/.temp/project-ref ]]; then
  echo "==> Step 1: Create Supabase project '$PROJECT_NAME'"
  DB_PASS="${SUPABASE_DB_PASSWORD:-$(openssl rand -base64 24)}"
  echo "    (save this db password somewhere safe if new project)"
  CREATE_OUT="$(supabase projects create "$PROJECT_NAME" \
    --org-id "$ORG_ID" \
    --region "$REGION" \
    --db-password "$DB_PASS" 2>&1)" || true
  echo "$CREATE_OUT"
  REF="$(echo "$CREATE_OUT" | awk '/REFERENCE ID/ {getline; print $3; exit}' | tr -d ' |')"
  if [[ -z "$REF" ]]; then
    REF="$(supabase projects list 2>/dev/null | awk -v n="$PROJECT_NAME" '$4==n {print $3; exit}')"
  fi
  if [[ -n "$REF" ]]; then
    supabase link --project-ref "$REF"
  else
    echo "Create succeeded but could not parse ref — run: supabase link"
    exit 1
  fi
fi

REF="$(cat supabase/.temp/project-ref 2>/dev/null || true)"
if [[ -z "$REF" ]]; then
  echo "Could not determine project ref. Run: supabase link"
  exit 1
fi

echo "    Project ref: $REF"
echo ""

# --- Step 2: push migration ---
echo "==> Step 2: Push database migration (platform_rankings)"
supabase db push
echo ""

# --- Step 3: write .env.local ---
echo "==> Step 3: Fetch API keys → .env.local"
ANON="$(supabase projects api-keys --project-ref "$REF" 2>/dev/null | awk '/anon/ {print $3}')"
URL="https://${REF}.supabase.co"

if [[ -z "$ANON" ]]; then
  echo "Could not fetch anon key. Copy from Supabase Dashboard → Settings → API"
else
  cat > .env.local <<EOF
# Generated by scripts/setup-supabase.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
EXPO_PUBLIC_SUPABASE_URL=${URL}
EXPO_PUBLIC_SUPABASE_ANON_KEY=${ANON}

# RevenueCat (add after App Store / Play setup)
EXPO_PUBLIC_REVENUECAT_IOS_KEY=
EXPO_PUBLIC_REVENUECAT_ANDROID_KEY=

# Dev: skip paywall for UI testing
EXPO_PUBLIC_DEV_PRO=false
EOF
  echo "    Wrote .env.local"
fi
echo ""

# --- Step 4: OAuth redirect URIs ---
REDIRECT="$(node -e "
  process.env.EXPO_OS='ios';
  const { makeRedirectUri } = require('expo-auth-session');
  console.log(makeRedirectUri({ scheme: 'limeboard', path: 'auth/callback' }));
" 2>/dev/null || echo 'limeboard://auth/callback')"

echo "==> Step 4: Auth URL configuration (Supabase Dashboard)"
echo "    Project → Authentication → URL configuration"
echo "    Site URL: limeboard://"
echo "    Redirect URLs (add each on its own line):"
echo "      ${REDIRECT}"
echo "      limeboard://auth/callback"
echo "      limeboard://**"
echo ""

echo "==> Step 5: Google OAuth (Google Cloud + Supabase)"
echo "    A) Google Cloud Console → APIs & Services → Credentials"
echo "       Create OAuth client → Web application"
echo "       Authorized redirect URI:"
echo "         ${URL}/auth/v1/callback"
echo "    B) Supabase → Authentication → Providers → Google"
echo "       Paste Client ID + Client Secret, enable provider"
echo ""

echo "==> Step 6: Apple Sign In (Supabase + Apple Developer)"
echo "    Supabase → Auth → Providers → Apple (enable)"
echo "    Apple Developer → Identifiers → app.limeboard.mobile → Sign in with Apple"
echo "    Add Services ID + key for Supabase if using web flow"
echo "    Native iOS uses signInWithIdToken (already wired in app)"
echo ""

echo "==> Step 7: Deploy rankings sync edge function"
echo "    supabase secrets set OPENROUTER_API_KEY=sk-or-..."
echo "    supabase functions deploy sync-rankings"
echo "    supabase functions invoke sync-rankings --no-verify-jwt"
echo "    Schedule daily in Dashboard → Edge Functions → sync-rankings → Cron"
echo ""

echo "==> Step 8: RevenueCat (after EAS dev client build)"
echo "    Create entitlement 'pro', products limeboard_pro_monthly / limeboard_pro_annual"
echo "    Add keys to .env.local"
echo ""

echo "==> Step 9: Run the app"
echo "    npx expo start"
echo ""
echo "Done. Project: ${URL}"
